//
//  PokemonDetailPresenter.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 19/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

final class PokemonDetailPresenter {

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()
    
    private unowned let view: PokemonDetailViewInterface
    private let interactor: PokemonDetailInteractorInterface
    private let wireframe: PokemonDetailWireframeInterface
    private let pokemonId: Int
    // MARK: - Lifecycle -

    init(pokemonId: Int, view: PokemonDetailViewInterface, interactor: PokemonDetailInteractorInterface, wireframe: PokemonDetailWireframeInterface) {
        self.pokemonId = pokemonId
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PokemonDetailPresenter: PokemonDetailPresenterInterface {
    
    func loadDetailData() {
        interactor.fetchPokemonDetail(pokemonId: pokemonId)
            .subscribe(onNext: { [weak self] (pokemon: Pokemon) in
                self?.view.drawPokemonInfo(pokemon: pokemon)
            })
            .disposed(by: disposeBag)
    }
}
