//
//  PokemonDetailInterfaces.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 19/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

protocol PokemonDetailWireframeInterface: WireframeInterface {
}

protocol PokemonDetailViewInterface: ViewInterface {
    func drawPokemonInfo(pokemon: Pokemon)
}

protocol PokemonDetailPresenterInterface: PresenterInterface {
    func loadDetailData()
}

protocol PokemonDetailInteractorInterface: InteractorInterface {
    func fetchPokemonDetail(pokemonId: Int) -> Observable<Pokemon>
}
