//
//  PokemonDetailWireframe.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 19/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PokemonDetailWireframe: BaseWireframe {

    // MARK: - Module setup -

    init(pokemonId: Int) {
        let moduleViewController = PokemonDetailViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = PokemonDetailInteractor()
        interactor.httpServices = Api.httpServices
        let presenter = PokemonDetailPresenter(pokemonId: pokemonId, view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension PokemonDetailWireframe: PokemonDetailWireframeInterface {
}
