//
//  PokemonDetailInteractor.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 19/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class PokemonDetailInteractor {
    
    // MARK: - Dependecies
    var httpServices: HttpServicesType!
}

// MARK: - Extensions -

extension PokemonDetailInteractor: PokemonDetailInteractorInterface {
    
    func fetchPokemonDetail(pokemonId: Int) -> Observable<Pokemon> {
        httpServices.request(to: .pokemonInfo(id: pokemonId))
            .mapObject(Pokemon.self)
    }
}
