//
//  PokeListInterfaces.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 17/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxDataSources

protocol PokeListWireframeInterface: WireframeInterface {
    func showPokemonDetail(pokemonId: Int)
}

protocol PokeListViewInterface: ViewInterface {
    func bindTableViewData(_ source: Observable<[PokeListSectionModel]>, withDataSource: PokeListDataSource)
}

protocol PokeListPresenterInterface: PresenterInterface {
    func loadPokemonList()
    func showPokemonDetail(pokemonId: Int)
    func searchPokemon(withCriteria criteria: String)
}

protocol PokeListInteractorInterface: InteractorInterface {
    func loadPokemonList() -> Observable<PokemonList>
    func loadPokemon(result: PokemonList.Result) -> Observable<Pokemon>
}
