//
//  PokeListWireframe.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 17/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PokeListWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = PokeListViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = PokeListInteractor()
        interactor.httpServices = Api.httpServices
        let presenter = PokeListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PokeListWireframe: PokeListWireframeInterface {
    
    func showPokemonDetail(pokemonId: Int) {
        let detail = PokemonDetailWireframe(pokemonId: pokemonId)
        navigationController?.pushWireframe(detail)
    }
}
