//
//  PokeListInteractor.swift
//  Pokedex
//
//  Created by Laura Sarmiento on 17/09/19.
//  Copyright (c) 2019 Medrar. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class PokeListInteractor {
    
    // MARK: - Dependecies
    var httpServices: HttpServicesType!
}

// MARK: - Extensions -

extension PokeListInteractor: PokeListInteractorInterface {
    
    func loadPokemonList() -> Observable<PokemonList> {
        httpServices.request(to: .listAllPokemons)
            .mapObject(PokemonList.self)
    }
    
    func loadPokemon(result: PokemonList.Result) -> Observable<Pokemon> {
        httpServices.request(toUrl: result.url)
            .mapObject(Pokemon.self)
    }
}
